//! Environment file generation

use anyhow::{Context, Result};
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

use super::Configuration;

/// Generate .env file from configuration
pub fn generate_env_file(config: &Configuration) -> Result<()> {
    let env_path = PathBuf::from(".env");

    // Check if .env already exists
    if env_path.exists() {
        // Backup existing file
        let backup_path = PathBuf::from(".env.backup");
        std::fs::copy(&env_path, &backup_path)
            .context("Failed to backup existing .env file")?;
        println!("Existing .env backed up to .env.backup");
    }

    // Create new .env file
    let mut file = File::create(&env_path)
        .context("Failed to create .env file")?;

    // Write configuration
    write_env_file(&mut file, config)?;

    println!(".env file created successfully");

    Ok(())
}

/// Write environment variables to file
fn write_env_file(file: &mut File, config: &Configuration) -> Result<()> {
    writeln!(file, "# Professional SMART Configuration")?;
    writeln!(file, "# Generated by setup wizard\n")?;

    writeln!(file, "# Database Configuration")?;
    writeln!(file, "DATABASE_URL={}", config.database_url)?;
    writeln!(file, "DATABASE_MAX_CONNECTIONS={}", config.database_max_connections)?;
    writeln!(file, "DATABASE_MIN_CONNECTIONS=5")?;
    writeln!(file, "DATABASE_CONNECT_TIMEOUT=30\n")?;

    writeln!(file, "# Application Configuration")?;
    writeln!(file, "RUST_LOG={}", config.log_level)?;
    writeln!(file, "RUST_BACKTRACE=0\n")?;

    writeln!(file, "# Performance Configuration")?;
    writeln!(file, "BATCH_SIZE={}", config.batch_size)?;
    writeln!(file, "MAX_WORKERS={}", config.max_workers)?;
    writeln!(file, "WORKER_TIMEOUT_SECONDS=300\n")?;

    writeln!(file, "# File Processing Configuration")?;
    writeln!(file, "INPUT_DIRECTORY={}", config.input_directory)?;
    writeln!(file, "PROCESSED_DIRECTORY={}", config.processed_directory)?;
    writeln!(file, "ERROR_DIRECTORY={}", config.error_directory)?;
    writeln!(file, "AUTO_PROCESS_FILES=false\n")?;

    writeln!(file, "# Rules Engine Configuration")?;
    writeln!(file, "ENABLE_RULES_ENGINE={}", config.enable_rules_engine)?;
    writeln!(file, "RULES_SEVERITY_THRESHOLD=Low")?;
    writeln!(file, "ENABLE_AUTO_CODING_SUGGESTIONS={}\n", config.enable_auto_coding_suggestions)?;

    writeln!(file, "# RVU Calculation Configuration")?;
    writeln!(file, "ENABLE_RVU_CALCULATION={}", config.enable_rvu_calculation)?;
    writeln!(file, "DEFAULT_GPCI_LOCALITY={}", config.default_gpci_locality)?;
    writeln!(file, "RVU_YEAR={}\n", config.rvu_year)?;

    writeln!(file, "# Validation Configuration")?;
    writeln!(file, "ENABLE_FILE_HASH_VALIDATION=true")?;
    writeln!(file, "ENABLE_PCN_VALIDATION=true")?;
    writeln!(file, "ENABLE_SERVICE_LINE_VALIDATION=true\n")?;

    writeln!(file, "# Audit and Logging Configuration")?;
    writeln!(file, "ENABLE_AUDIT_TRAIL=true")?;
    writeln!(file, "LOG_DIRECTORY={}", config.log_directory)?;
    writeln!(file, "LOG_ROTATION_SIZE_MB=100")?;
    writeln!(file, "LOG_RETENTION_DAYS=30\n")?;

    Ok(())
}
