# EDI Claims Processing System Configuration
# Database Configuration
database:
  postgresql:
    host: localhost
    port: 5432
    database: claims_processing # Production: Use environment variables or secrets management for credentials
    user: postgres             # Production: Use environment variables or secrets management for credentials
    password: admin            # Production: Use environment variables or secrets management for credentials
    min_connections: 2
    max_connections: 10

  sqlserver:
    connection_string: "DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;DATABASE=validation_results;UID=sa;PWD=ClearToFly1"
    pool_size: 10

# Processing Configuration
processing:
  chunk_size: 500
  max_workers: 4
  memory_limit_percent: 70
  cpu_limit_percent: 80
  batch_size: 1000
  parser_cache_ttl_seconds: 300 # TTL for claim count cache in parser (seconds)

# ML Training Configuration
ml_training:
  training_chunk_size: 10000
  memory_limit_percent: 70
  model_output_path: "models/filter_predictor.pkl"

# Validation Configuration
validation:
  ml_model_path: "models/filter_predictor.pkl"
  prediction_threshold: 0.3
  max_filters_per_claim: 10

# Storage Configuration
storage:
  batch_size: 1000
  max_retries: 3

# Monitoring Configuration
monitoring:
  prometheus_port: 8000
  log_level: INFO
  enable_email_alerts: false  # Disabled since no email config
  monitoring_interval: 30

# Email Configuration - disabled for now
email:
  enabled: false
  smtp_server: smtp.company.com
  smtp_port: 587
  username: edi-system@company.com
  password: "your_plain_smtp_password"  # Use plain text or disable email
  from_email: edi-system@company.com
  recipients:
    - admin@company.com
    - ops@company.com
  severity_levels:
    - ERROR
    - CRITICAL

# Rule Generation Configuration
rule_generation:
  min_support: 0.01
  min_confidence: 0.5
  min_lift: 1.1
  data_load_limit: 10000 # Max records to load for rule generation

# Removed encryption_key and password_encrypted to disable encryption