# Fix MigrationsFragment.wxs generated by Heat.exe
param(
    [string]$InputFile = "MigrationsFragment_temp.wxs",
    [string]$OutputFile = "MigrationsFragment.wxs"
)

$content = Get-Content $InputFile -Raw

# Fix paths - add migrations\ subdirectory
$content = $content -replace 'Source="\$\(var\.SolutionDir\)\\', 'Source="$(var.SolutionDir)migrations\'

# Add Win64="yes" to all Component tags
$content = $content -replace '<Component Id="([^"]+)" Guid="([^"]+)">', '<Component Id="$1" Guid="$2" Win64="yes">'

# Remove README.md component (entire Component block)
$content = $content -replace '(?s)<Component Id="cmp[^"]*" Guid="[^"]*" Win64="yes">\s*<File[^>]*README\.md[^>]*/>\s*</Component>\s*', ''

# Remove README.md ComponentRef
$content = $content -replace '<ComponentRef Id="cmp[^"]*"\s*/>\s*(?=\s*</ComponentGroup>)', ''

Set-Content $OutputFile $content -NoNewline

Write-Host "MigrationsFragment.wxs processed successfully"
