' WriteConfig.vbs - Create .env configuration file with database settings

' Helper function to write to MSI log
Sub LogMessage(message)
    Dim record
    Set record = Session.Installer.CreateRecord(1)
    record.StringData(0) = "Professional SMART Installer: [1]"
    record.StringData(1) = message
    Session.Message &H04000000, record
End Sub

Function WriteConfig()
    LogMessage "WriteConfig: Starting configuration file creation"

    ' Get installer properties using CustomActionData
    Dim customData
    customData = Session.Property("CustomActionData")
    LogMessage "WriteConfig: CustomActionData = " & customData

    ' Parse the custom action data (formatted as: host|port|name|user|password|installdir|programdata)
    Dim parts
    parts = Split(customData, "|")

    If UBound(parts) < 6 Then
        LogMessage "WriteConfig: ERROR - Not enough parameters. Expected 7, got " & (UBound(parts) + 1)
        WriteConfig = 1  ' Return success to not block install
        Exit Function
    End If

    Dim dbHost, dbPort, dbName, dbUser, dbPassword, installFolder, programDataFolder
    dbHost = parts(0)
    dbPort = parts(1)
    dbName = parts(2)
    dbUser = parts(3)
    dbPassword = parts(4)
    installFolder = parts(5)
    programDataFolder = parts(6)

    LogMessage "WriteConfig: DB_HOST = " & dbHost
    LogMessage "WriteConfig: DB_PORT = " & dbPort
    LogMessage "WriteConfig: DB_NAME = " & dbName
    LogMessage "WriteConfig: DB_USER = " & dbUser
    LogMessage "WriteConfig: DB_PASSWORD = " & String(Len(dbPassword), "*")
    LogMessage "WriteConfig: INSTALLFOLDER = " & installFolder
    LogMessage "WriteConfig: ProgramData = " & programDataFolder

    ' Ensure paths end with backslash
    If Right(installFolder, 1) <> "\" Then
        installFolder = installFolder & "\"
    End If
    If Right(programDataFolder, 1) <> "\" Then
        programDataFolder = programDataFolder & "\"
    End If

    ' Build paths
    Dim configPath
    configPath = programDataFolder & "Professional SMART\config\.env"
    LogMessage "WriteConfig: Target config path = " & configPath

    ' Build PostgreSQL connection string (use postgres:// for compatibility)
    Dim connectionString
    connectionString = "postgres://" & dbUser & ":" & dbPassword & "@" & dbHost & ":" & dbPort & "/" & dbName
    LogMessage "WriteConfig: Connection string = postgres://" & dbUser & ":****@" & dbHost & ":" & dbPort & "/" & dbName

    ' Create FileSystemObject
    Dim fso
    Set fso = CreateObject("Scripting.FileSystemObject")
    LogMessage "WriteConfig: FileSystemObject created"

    ' Check if directory exists
    Dim configDir
    configDir = programDataFolder & "Professional SMART\config"
    If fso.FolderExists(configDir) Then
        LogMessage "WriteConfig: Config directory exists: " & configDir
    Else
        LogMessage "WriteConfig: WARNING - Config directory does not exist: " & configDir
    End If

    ' Check if config file already exists (upgrade scenario)
    If fso.FileExists(configPath) Then
        LogMessage "WriteConfig: Config file already exists - creating backup"

        ' Create backup of existing config
        Dim backupPath
        backupPath = configPath & ".backup_" & Year(Now()) & Right("0" & Month(Now()), 2) & Right("0" & Day(Now()), 2) & "_" & Right("0" & Hour(Now()), 2) & Right("0" & Minute(Now()), 2) & Right("0" & Second(Now()), 2)

        On Error Resume Next
        fso.CopyFile configPath, backupPath
        If Err.Number = 0 Then
            LogMessage "WriteConfig: Backup created: " & backupPath
        Else
            LogMessage "WriteConfig: WARNING - Failed to create backup: " & Err.Description
        End If
        On Error GoTo 0

        ' During upgrade, preserve existing config and only add new keys
        LogMessage "WriteConfig: Upgrade detected - preserving existing configuration"
        WriteConfig = 1
        Set fso = Nothing
        Exit Function
    End If

    ' Write configuration file directly (fresh install only)
    On Error Resume Next
    Dim configFile
    Set configFile = fso.CreateTextFile(configPath, True)

    If Err.Number <> 0 Then
        LogMessage "WriteConfig: ERROR - Failed to create config file. Error: " & Err.Description & " (Code: " & Err.Number & ")"
        WriteConfig = 1  ' Return success to not block install
        Exit Function
    End If

    LogMessage "WriteConfig: Config file created successfully"

    ' Write all configuration lines
    configFile.WriteLine "# Professional SMART Configuration"
    configFile.WriteLine "# Generated by installer on " & Now()
    configFile.WriteLine ""
    configFile.WriteLine "# Database Configuration"
    configFile.WriteLine "DATABASE_URL=" & connectionString
    configFile.WriteLine "DB_HOST=" & dbHost
    configFile.WriteLine "DB_PORT=" & dbPort
    configFile.WriteLine "DB_NAME=" & dbName
    configFile.WriteLine "DB_USER=" & dbUser
    configFile.WriteLine "DB_PASSWORD=" & dbPassword
    configFile.WriteLine ""
    configFile.WriteLine "# Service Configuration"
    configFile.WriteLine "LOG_LEVEL=info"
    configFile.WriteLine "RUST_LOG=info"
    configFile.WriteLine ""
    configFile.WriteLine "# File Processing"
    configFile.WriteLine "INPUT_DIR=" & installFolder & "data\input"
    configFile.WriteLine "PROCESSED_DIR=" & installFolder & "data\processed"
    configFile.WriteLine "ERROR_DIR=" & installFolder & "data\error"
    configFile.WriteLine ""
    configFile.WriteLine "# WebSocket Configuration"
    configFile.WriteLine "STREAMING_ENABLE_WEBSOCKET=true"
    configFile.WriteLine "WEBSOCKET_HOST=127.0.0.1:8080"
    configFile.WriteLine ""
    configFile.WriteLine "# Worker Configuration"
    configFile.WriteLine "WORKER_THREADS=4"
    configFile.WriteLine "BATCH_SIZE=100"

    configFile.Close
    On Error GoTo 0

    If Err.Number <> 0 Then
        LogMessage "WriteConfig: ERROR - Failed to write config file. Error: " & Err.Description
    Else
        LogMessage "WriteConfig: Configuration file written successfully to " & configPath
    End If

    ' Return success (1 = success in VBScript custom actions)
    WriteConfig = 1

    Set configFile = Nothing
    Set fso = Nothing

    LogMessage "WriteConfig: Completed"
End Function
